name: mem-profiler

channels:
  - conda-forge

dependencies:
  # Common packages
  - ccache
  - cmake>=3.21
  - hdf5>1.14.0,<1.15 # gets libcurl>=8.4
  - jemalloc=5.2.0 # We have noticed 5.2.1 can cause a hang on older glibc versions (Cent OS 7, Ubuntu 18.04). Observed with import CaChannel and also our MeierTest.
  - nexus=4.4.*
  - ninja>=1.10.2
  - pre-commit
  - python=3.10.*
  # compiler
  - gxx_linux-64==12.*
  # Development tooling
  - cppcheck==2.14.2
  - pre-commit>=2.12.0
